Convolution 1D menggunakan Numpy

In [1]:
import numpy as np

a = np.array([3, 2, 1])
b = np.array([1, 2, 3, 4, 5])

print("a:", a)
print("b:", b)

print("a * b:", np.convolve(a, b))

a: [3 2 1]
b: [1 2 3 4 5]
a * b: [ 3  8 14 20 26 14  5]


Convolution 2D menggunakan Scipy. Numpy tidak memiliki API convolution 2D.

In [7]:
from scipy import signal

c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.array([[1, 1], [1, 1]])

print(f"c:\n{c}\n")
print(f"d:\n{d}\n")

print(f"c * d:\n{signal.convolve2d(c, d, mode='valid')}\n")

c:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

d:
[[1 1]
 [1 1]]

c * d: [[12 16]
 [24 28]]


Edge detection untuk mendapatkan posisi garis dari simple matrix menggunakan convolution

In [12]:
import numpy as np
from scipy import signal

# edge detection
matrix = np.array([
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
])

prewitt_filter = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1],
])

sober_filter = np.array([
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1],
])

scharr_filter = np.array([
    [3, 0, -3],
    [10, 0, -10],
    [3, 0, -3],
])

print(matrix)
print(prewitt_filter)
print(signal.convolve2d(matrix, prewitt_filter, mode='valid'))

print(sober_filter)
print(signal.convolve2d(matrix, sober_filter, mode='valid'))

print(scharr_filter)
print(signal.convolve2d(matrix, scharr_filter, mode='valid'))

[[10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]]
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]
[[  0 -30 -30   0]
 [  0 -30 -30   0]
 [  0 -30 -30   0]
 [  0 -30 -30   0]]
[[ 1  0 -1]
 [ 2  0 -2]
 [ 1  0 -1]]
[[  0 -40 -40   0]
 [  0 -40 -40   0]
 [  0 -40 -40   0]
 [  0 -40 -40   0]]
[[  3   0  -3]
 [ 10   0 -10]
 [  3   0  -3]]
[[   0 -160 -160    0]
 [   0 -160 -160    0]
 [   0 -160 -160    0]
 [   0 -160 -160    0]]
